version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@users_db:5432/users_db
    depends_on:
      - users_db

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@payment_db:5432/payment_db
    depends_on:
      - payment_db

  users_db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  payment_db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

volumes:
  users_db_data:
  payment_db_data:
